/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

////////////////////lab08 Start/////////////////

    @Test public void quoteRandom(){
    String result="Quote{tags=[attributed-no-source], author='Marilyn Monroe', likes='18651 likes', text=' “I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love. '}";
        assertEquals("this test for class quote json file: ",result,String.valueOf(App.randomQuote("../Ahmad.json")));
    }

////////////////////lab08 End/////////////////

////////////////////lab09 Start/////////////////

    @Test public void quoteRandomRes(){
        assertNotNull("this test for class quote URL: ", App.randomQuoteRes());
    }

////////////////////lab09 End/////////////////

}
